apiVersion: v1
kind: ReplicationController
metadata:
  name: tester
  labels:
    name: tester
spec:
  replicas: 1
  selector:
    name: tester
  template:
    metadata:
      labels:
        name: tester
    spec:
      containers:
      - name: tester
        image: raftis/tester:latest
