apiVersion: v1
kind: ReplicationController
metadata:
  name: etcd
  labels:
    name: etcd
spec:
  replicas: 1
  selector:
    name: etcd
  template:
    metadata:
      labels:
        name: etcd
    spec:
      containers:
      - name: etcd
        image: coreos/etcd:latest
        ports:
        - containerPort: 4001
        - containerPort: 2379
        - containerPort: 2380
