apiVersion: v1
kind: Service
metadata:
  name: raftis
  labels:
    name: raftis
spec:
  type: LoadBalancer
  ports:
    - name: 'raftis'
      port: 4001
      targetPort: 4001
  selector:
    name: raftis
