apiVersion: v1
kind: Service
metadata:
  name: raftis
  labels:
    name: raftis
spec:
  type: LoadBalancer
  ports:
    - name: 'raftis'
      port: 6379
      targetPort: 6379
  selector:
    name: raftis
