apiVersion: v1
kind: ReplicationController
metadata:
  name: raftis
  labels:
    name: raftis
spec:
  replicas: 9
  selector:
    name: raftis
  template:
    metadata:
      labels:
        name: raftis
    spec:
      containers:
      - name: raftis
        image: raftis/raftis:latest
        ports:
        - containerPort: 1103
        - containerPort: 6379

        volumeMounts:
        - mountPath: /var/raftis
          name: data
      volumes:
        - name: data
          emptyDir: {}
